export const SET_USER_EMAIL_LOGIN = 'SET_USER_EMAIL_LOGIN'
export const SET_USER_PASSWORD_LOGIN = 'SET_USER_PASSWORD_LOGIN'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_LOGGED_USER = 'SET_LOGGED_USER'
export const SET_WRONG_USER_PASSWORD = 'SET_WRONG_USER_PASSWORD'
export const SET_LOADING_LOGIN_BUTTON = 'SET_LOADING_LOGIN_BUTTON'
export const SET_SIDEBAR_MENU = 'SET_SIDEBAR_MENU'

